//All Videos Data



export const videos = [
    {
      _id: 19,
      title: 'Origami Swan - Simple and Elegant',
      views: 2879,
      chips: ['origami', 'swan', 'paper', 'elegant'],
      thumbnail: 'https://i.ytimg.com/vi/Tt47o-DyJXo/sddefault.jpg',
      src: 'https://www.youtube.com/embed/Tt47o-DyJXo',
      category: 'Origami',
      creator: 'PaperCraftPro',
    },
    {
      _id: 20,
      title: 'Kirigami Flower Bouquet - Beautiful Handmade Gift',
      views: 1756,
      chips: ['kirigami', 'flower bouquet', 'paper', 'gift'],
      thumbnail: 'https://i.ytimg.com/vi/CG685PXRrjI/sddefault.jpg',
      src: 'https://www.youtube.com/embed/CG685PXRrjI',
      category: 'Kirigami',
      creator: 'Crafty Delights',
    },
    {
      _id: 21,
      title: 'Sculpting Animals from Polymer Clay - Step by Step Guide',
      views: 2251,
      chips: ['sculpture', 'polymer clay', 'animals', 'crafts'],
      thumbnail: 'https://i.ytimg.com/vi/CW5Qgb4n49c/sddefault.jpg',
      src: 'https://www.youtube.com/embed/CW5Qgb4n49c',
      category: 'Clay Modeling',
      creator: 'CraftyCritters',
    },
    {
      _id: 22,
      title: 'Stop Motion Short Film - Adventure in Toyland',
      views: 3172,
      chips: ['stop motion', 'short film', 'toyland', 'adventure'],
      thumbnail: 'https://i.ytimg.com/vi/ij3IbplMisA/sddefault.jpg',
      src: 'https://www.youtube.com/embed/ij3IbplMisA',
      category: 'Stop Motion',
      creator: 'ToyStoryMakers',
    },
    {
      _id: 23,
      title: 'Handmade Pottery Vases - Decorating with Ceramic Glaze',
      views: 2879,
      chips: ['pottery', 'clay', 'vases', 'ceramic glaze'],
      thumbnail: 'https://i.ytimg.com/vi/nvBxX7vteqA/sddefault.jpg',
      src: 'https://www.youtube.com/embed/nvBxX7vteqA',
      category: 'Pottery',
      creator: 'CeramicArtistry',
    },
    {
      _id: 24,
      title: 'Quilling Art Techniques - Creating Intricate Designs',
      views: 1756,
      chips: ['quilling', 'paper art', 'techniques', 'intricate designs'],
      thumbnail: 'https://i.ytimg.com/vi/NezgcmZv198/sddefault.jpg',
      src: 'https://www.youtube.com/embed/NezgcmZv198',
      category: 'Quilling',
      creator: 'ArtfulQuills',
    },
    {
      _id: 25,
      title: 'Origami Crane Mobile - DIY Home Decor',
      views: 2251,
      chips: ['origami', 'crane', 'mobile', 'paper', 'home decor'],
      thumbnail: 'https://i.ytimg.com/vi/dc95upuVAg8/sddefault.jpg',
      src: 'https://www.youtube.com/embed/dc95upuVAg8',
      category: 'Origami',
      creator: 'HomeCraftHacks',
    },
    {
      _id: 26,
      title: 'Kirigami Birthday Pop-Up Box - Surprise Gift',
      views: 3172,
      chips: ['kirigami', 'birthday pop-up box', 'paper', 'surprise gift'],
      thumbnail: 'https://i.ytimg.com/vi/BcJiH0a2Mm0/sddefault.jpg',
      src: 'https://www.youtube.com/embed/BcJiH0a2Mm0',
      category: 'Kirigami',
      creator: 'GiftsFromHeart',
    },
    {
      _id: 27,
      title: 'Sculpting Fantasy Creatures - Unleash Your Imagination',
      views: 2879,
      chips: ['sculpture', 'fantasy creatures', 'clay', 'imagination'],
      thumbnail: 'https://i.ytimg.com/vi/2mMWiqUV_zQ/sddefault.jpg',
      src: 'https://www.youtube.com/embed/2mMWiqUV_zQ',
      category: 'Clay Modeling',
      creator: 'FantasyArtWorks',
    },
    {
      _id: 28,
      title: 'Stop Motion Animation Contest - Show Your Skills',
      views: 1756,
      chips: ['stop motion', 'animation contest', 'competition'],
      thumbnail: 'https://i.ytimg.com/vi/fARjc4bwvfc/sddefault.jpg',
      src: 'https://www.youtube.com/embed/fARjc4bwvfc',
      category: 'Stop Motion',
      creator: 'AnimateMasters',
    },
    {
      _id: 29,
      title: 'Pottery Wheel Techniques - Creating Stunning Bowls',
      views: 2251,
      chips: ['pottery', 'clay', 'wheel techniques', 'bowls'],
      thumbnail: 'https://i.ytimg.com/vi/kwr5zIniGAk/sddefault.jpg',
      src: 'https://www.youtube.com/embed/kwr5zIniGAk',
      category: 'Pottery',
      creator: 'ArtisticPots',
    },
    {
      _id: 30,
      title: 'Quilling Greeting Cards - Handmade Cards for Every Occasion',
      views: 3172,
      chips: ['quilling', 'greeting cards', 'paper', 'occasions'],
      thumbnail: 'https://i.ytimg.com/vi/k6RUK-PXKzc/sddefault.jpg',
      src: 'https://www.youtube.com/embed/k6RUK-PXKzc',
      category: 'Quilling',
      creator: 'CraftyGreetings',
    },
  
    {
      _id: 31,
      title: 'Origami Elephant - Step-by-Step Tutorial',
      views: 2879,
      chips: ['origami', 'elephant', 'paper', 'tutorial'],
      thumbnail: 'https://i.ytimg.com/vi/zgyMARIDFSA/sddefault.jpg',
      src: 'https://www.youtube.com/embed/zgyMARIDFSA"',
      category: 'Origami',
      creator: 'OrigamiWonderland',
    },
    
    {
      _id: 32,
      title: 'Kirigami Art Collage - Combining Paper Shapes',
      views: 1756,
      chips: ['kirigami', 'art collage', 'paper', 'shapes'],
      thumbnail: 'https://i.ytimg.com/vi/pyQiV_lWECo/sddefault.jpg',
      src: 'https://www.youtube.com/embed/pyQiV_lWECo',
      category: 'Kirigami',
      creator: 'CreativeFolds',
    },
    {
      _id: 33,
      title: 'Sculpting Realistic Portraits - Mastering Human Faces',
      views: 2251,
      chips: ['sculpture', 'realistic portraits', 'clay', 'human faces'],
      thumbnail: 'https://i.ytimg.com/vi/-aMqptJD5uE/sddefault.jpg',
      src: 'https://www.youtube.com/embed/-aMqptJD5uE',
      category: 'Clay Modeling',
      creator: 'PortraitsInClay',
    },

    {
      _id: 34,
      title: 'Stop Motion Animation Tips and Tricks',
      views: 3172,
      chips: ['stop motion', 'animation', 'tips', 'tricks'],
      thumbnail: 'https://i.ytimg.com/vi/CY6l2B4mXvw/sddefault.jpg',
      src: 'https://www.youtube.com/embed/CY6l2B4mXvw',
      category: 'Stop Motion',
      creator: 'AnimateMagic',
    },
    {
      _id: 35,
      title: 'Pottery Art Exhibition - Celebrating Local Artists',
      views: 2879,
      chips: ['pottery', 'clay', 'art exhibition', 'local artists'],
      thumbnail: 'https://i.ytimg.com/vi/FsX8-LNSySE/sddefault.jpg',
      src: 'https://www.youtube.com/embed/FsX8-LNSySE',
      category: 'Pottery',
      creator: 'ArtisticExpressions',
    },
    {
      _id: 36,
      title: 'Quilling 3D Wall Art - Adding Depth to Paper Designs',
      views: 1756,
      chips: ['quilling', '3d wall art', 'paper', 'designs'],
      thumbnail: 'https://i.ytimg.com/vi/TIOJJPUVtgM/sddefault.jpg',
      src: 'https://www.youtube.com/embed/TIOJJPUVtgM',
      category: 'Quilling',
      creator: 'PaperArtDimensions',
    },
  ]